### ISSUE TITLE
Propagated Labels

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/gluon#10]
As an operator, I would like to be able to propagate K8s labels to the resources that Gluon is creating for me.

Here's a sketch of an idea:

```
apiVersion: gluon.starkandwayne.com/v1alpha1
kind: BOSHDeployment
spec:
  template:
    labels:
      env: prod
```
