### ISSUE TITLE
New Variable Source: Metadata Reference

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/gluon#11]
This one is highly specific.

I would like to be able to rename deployments that support it by re-using the BOSHDeployment objects name.  To do this, the `vars` section needs a metadata reference, like environment variables on Pods have:

```
kind: BOSHDeployment
metadata:
  name: a-bosh-deployment
spec:
  vars:
    - name: deployment_name
      metadataReference:
        path: .metadata.name
```
