### ISSUE TITLE
Service Account Provisioning / RBAC in Gluon Deployment

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/gluon#7]
At the end of a stock (from-YAMLs) Gluon Controller deployment's first director standup, we fail to set the vars configmap / secret:

```
##################################
#
# Saving credentials / state file
+ set +x
#   to Secret cab1-secrets
#  and ConfigMap cab1-state
#  (respectively)
#
##################################


Cluster "here" set.
User "sa" set.
Context "here" created.
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "/v1, Resource=configmaps", GroupVersionKind: "/v1, Kind=ConfigMap"
Name: "cab1-state", Namespace: "default"
from server for: "/dev/fd/63": configmaps "cab1-state" is forbidden: User "system:serviceaccount:default:default" cannot get resource "configmaps" in API group "" in the namespace "default"
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "/v1, Resource=secrets", GroupVersionKind: "/v1, Kind=Secret"
Name: "cab1-secrets", Namespace: "default"
from server for: "/dev/fd/63": secrets "cab1-secrets" is forbidden: User "system:serviceaccount:default:default" cannot get resource "secrets" in API group "" in the namespace "default"
```

To fix this, we need a service account for Gluon Controller to use that can `[get, create, update, patch, watch, list]` configmaps and secrets in all namespaces.

I applied this as a role + binding in the namespace I was doing BOSH things in:
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gluon-deployer
rules:
- apiGroups: ['']
  resources: [configmaps, secrets]
  verbs: [get, list, watch, create, update, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-is-a-gluon-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gluon-deployer
subjects:
- kind: ServiceAccount
  name: default
```

Figure out a better, more permanent way of doing this, without losing the ability to store the secrets _in_ the namespace alongside the BOSH* resources.
