### ISSUE TITLE
Support Custom (inline) Ops Files

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/gluon#9]
As someone who has to consume `-deployment` releases that are 100% outside of my control, I would like the ability to insert a go-patch ops file or three, of my own design, from inside the BOSHDeployment resource definition itself.

Something like:

```
---
apiVersion: gluon.starkandwayne.com/v1alpha1
kind: BOSHDeployment
metadata:
  name: proto
spec:
  repo: https://github.com/cloudfoundry/bosh-deployment
  ref:  master
  entrypoint: bosh.yml
  ops:
    - gcp/cpi.yml
    - jumpbox-user.yml
    - my/inline.yml   # <---------- this is a custom ops file, defined below

  vars:
    - configMap:
        name: proto-bosh-gcp

  customOpsFiles:
    - name: my/inline.yml # <----- this matches how we referred it above
       content: |
         ---
         - type: replace
           path: /name
           value: my-new-name
```

should work just fine.
